# -*- coding: utf-8 -*-
"""practice_coding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xpE4GXBXiM-Z8jUF8Wh3jsMMsFOJCQx_

# 2-01 숫자형
"""

# 파이썬에서는 정수,실수,8진수,16진수 숫자 형태로 이루어진 자료형들이 있다.

a = 123
a = -178
a = 0

# 양의정수 / 음의 정수 / 0 / 변수 a에 대입한 예

a = 1.2
a = -3.45

# 실수형은 소수점이 포함된 숫자 / 변수 a 대입한 예

a = 4.24E10
a = 4.24e-10

# 컴퓨터식 지수 표현

a = 0o177

# 8진수는 0o or 0O (알파벳 소문자 or 대문자)

a = 0x8ff
b = 0xABC

# 16진수 형ㅎ식 파이썬에서는 잘 사용하지 않음

## 숫자형을 활용하기 위한 연산자

a = 3
b = 4

a + b

a * b

a / b

a ** b

7 % 3 # 나머지값이 나오는 연산

7 // 4 # 몫을 나오는 연산

# 끝.